[ui]
diff-formatter = ["difft", "--color=always"]
editor = "nvim"

[merge-tools.difft-plain]
program = "difft"
diff-args = ["--color=never", "$left", "$right"]

[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"

[aliases]
dfp = ["diff", "--tool", "difft-plain"]
dft = ["diff", "--tool", "difft"]
logn = ["log", "--no-pager"]
tug = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "@"]
